import type { Conta } from "../types/conta";

export function getMockContasByClient(clientId: string): Conta[] {
  return [
    {
      id: `${clientId}-conta-1`,
      clientId,
      institution: "Itaú",
      accountName: "Conta Principal",
      numeroConta: "12345-6",
      tipo: "Automático",
      competencia: "Fev/2026",
      status: "Ativa",
      esporadico: false,
      ativoDesde: "2024-01-15",
    },
    {
      id: `${clientId}-conta-2`,
      clientId,
      institution: "XP",
      accountName: "Investimentos",
      numeroConta: "98765-4",
      tipo: "Manual",
      competencia: "Fev/2026",
      status: "Ativa",
      esporadico: false,
      ativoDesde: "2024-03-10",
    },
    {
      id: `${clientId}-conta-3`,
      clientId,
      institution: "BTG",
      accountName: "Holding Familiar",
      numeroConta: "55432-1",
      tipo: "Manual Cliente",
      competencia: "Jan/2026",
      status: "Ativa",
      esporadico: true,
      ativoDesde: "2025-06-01",
    },
    {
      id: `${clientId}-conta-4`,
      clientId,
      institution: "Santander",
      accountName: "Conta Corrente",
      numeroConta: "33210-8",
      tipo: "Manual",
      competencia: "Dez/2025",
      status: "Desativada",
      esporadico: false,
      ativoDesde: "2023-05-20",
      desativadoDesde: "2025-12-01",
    },
    {
      id: `${clientId}-conta-5`,
      clientId,
      institution: "Safra",
      accountName: "Previdência",
      numeroConta: "77890-3",
      tipo: "Automático",
      competencia: "Fev/2026",
      status: "Ativa",
      esporadico: false,
      ativoDesde: "2024-08-15",
    },
  ];
}
