import type { Extrato } from "../types/extrato";

const clients = [
  { id: "c1", name: "Ana Souza", initials: "AS" },
  { id: "c2", name: "Roberto Mendes", initials: "RM" },
  { id: "c3", name: "João Pereira", initials: "JP" },
  { id: "c4", name: "Maria Oliveira", initials: "MO" },
  { id: "c5", name: "Carlos Silva", initials: "CS" },
];

const institutions = [
  "Itaú Personalité",
  "XP Investimentos",
  "BTG Pactual",
  "Santander Select",
  "Safra",
];

function buildExtratos(month: Date): Extrato[] {
  return [
    // Ana Souza
    {
      id: "e1",
      clientId: "c1",
      clientName: "Ana Souza",
      clientInitials: "AS",
      institution: "Itaú Personalité",
      accountType: "Principal",
      collectionMethod: "Automático",
      status: "Recebido",
      referenceMonth: month,
      receivedAt: "2026-02-20",
    },
    {
      id: "e2",
      clientId: "c1",
      clientName: "Ana Souza",
      clientInitials: "AS",
      institution: "XP Investimentos",
      accountType: "Principal",
      collectionMethod: "Manual",
      status: "Pendente",
      referenceMonth: month,
    },
    {
      id: "e3",
      clientId: "c1",
      clientName: "Ana Souza",
      clientInitials: "AS",
      institution: "BTG Pactual",
      accountType: "Holding",
      collectionMethod: "Manual",
      status: "Solicitado",
      referenceMonth: month,
      requestedAt: "2026-02-15",
    },
    // Roberto Mendes
    {
      id: "e4",
      clientId: "c2",
      clientName: "Roberto Mendes",
      clientInitials: "RM",
      institution: "Santander Select",
      accountType: "Principal",
      collectionMethod: "Automático",
      status: "Consolidado",
      referenceMonth: month,
      consolidatedAt: "2026-02-25",
    },
    {
      id: "e5",
      clientId: "c2",
      clientName: "Roberto Mendes",
      clientInitials: "RM",
      institution: "XP Investimentos",
      accountType: "Filho",
      collectionMethod: "Manual",
      status: "Pendente",
      referenceMonth: month,
    },
    {
      id: "e6",
      clientId: "c2",
      clientName: "Roberto Mendes",
      clientInitials: "RM",
      institution: "Itaú Personalité",
      accountType: "Principal",
      collectionMethod: "Automático",
      status: "Recebido",
      referenceMonth: month,
      receivedAt: "2026-02-22",
    },
    {
      id: "e7",
      clientId: "c2",
      clientName: "Roberto Mendes",
      clientInitials: "RM",
      institution: "Safra",
      accountType: "Holding",
      collectionMethod: "Manual",
      status: "Solicitado",
      referenceMonth: month,
      requestedAt: "2026-02-18",
    },
    // João Pereira
    {
      id: "e8",
      clientId: "c3",
      clientName: "João Pereira",
      clientInitials: "JP",
      institution: "BTG Pactual",
      accountType: "Principal",
      collectionMethod: "Automático",
      status: "Pendente",
      referenceMonth: month,
    },
    {
      id: "e9",
      clientId: "c3",
      clientName: "João Pereira",
      clientInitials: "JP",
      institution: "Itaú Personalité",
      accountType: "Filho",
      collectionMethod: "Manual",
      status: "Recebido",
      referenceMonth: month,
      receivedAt: "2026-02-19",
    },
    {
      id: "e10",
      clientId: "c3",
      clientName: "João Pereira",
      clientInitials: "JP",
      institution: "XP Investimentos",
      accountType: "Principal",
      collectionMethod: "Automático",
      status: "Consolidado",
      referenceMonth: month,
      consolidatedAt: "2026-02-26",
    },
    {
      id: "e11",
      clientId: "c3",
      clientName: "João Pereira",
      clientInitials: "JP",
      institution: "Safra",
      accountType: "Holding",
      collectionMethod: "Manual",
      status: "Solicitado",
      referenceMonth: month,
      requestedAt: "2026-02-12",
    },
    // Maria Oliveira
    {
      id: "e12",
      clientId: "c4",
      clientName: "Maria Oliveira",
      clientInitials: "MO",
      institution: "Santander Select",
      accountType: "Principal",
      collectionMethod: "Automático",
      status: "Pendente",
      referenceMonth: month,
    },
    {
      id: "e13",
      clientId: "c4",
      clientName: "Maria Oliveira",
      clientInitials: "MO",
      institution: "BTG Pactual",
      accountType: "Filho",
      collectionMethod: "Manual",
      status: "Pendente",
      referenceMonth: month,
    },
    {
      id: "e14",
      clientId: "c4",
      clientName: "Maria Oliveira",
      clientInitials: "MO",
      institution: "XP Investimentos",
      accountType: "Principal",
      collectionMethod: "Automático",
      status: "Recebido",
      referenceMonth: month,
      receivedAt: "2026-02-21",
    },
    {
      id: "e15",
      clientId: "c4",
      clientName: "Maria Oliveira",
      clientInitials: "MO",
      institution: "Itaú Personalité",
      accountType: "Holding",
      collectionMethod: "Manual",
      status: "Consolidado",
      referenceMonth: month,
      consolidatedAt: "2026-02-24",
    },
    // Carlos Silva
    {
      id: "e16",
      clientId: "c5",
      clientName: "Carlos Silva",
      clientInitials: "CS",
      institution: "Safra",
      accountType: "Principal",
      collectionMethod: "Automático",
      status: "Solicitado",
      referenceMonth: month,
      requestedAt: "2026-02-16",
    },
    {
      id: "e17",
      clientId: "c5",
      clientName: "Carlos Silva",
      clientInitials: "CS",
      institution: "XP Investimentos",
      accountType: "Filho",
      collectionMethod: "Manual",
      status: "Pendente",
      referenceMonth: month,
    },
    {
      id: "e18",
      clientId: "c5",
      clientName: "Carlos Silva",
      clientInitials: "CS",
      institution: "BTG Pactual",
      accountType: "Principal",
      collectionMethod: "Automático",
      status: "Consolidado",
      referenceMonth: month,
      consolidatedAt: "2026-02-27",
    },
    {
      id: "e19",
      clientId: "c5",
      clientName: "Carlos Silva",
      clientInitials: "CS",
      institution: "Santander Select",
      accountType: "Holding",
      collectionMethod: "Manual",
      status: "Recebido",
      referenceMonth: month,
      receivedAt: "2026-02-23",
    },
    {
      id: "e20",
      clientId: "c5",
      clientName: "Carlos Silva",
      clientInitials: "CS",
      institution: "Itaú Personalité",
      accountType: "Principal",
      collectionMethod: "Automático",
      status: "Pendente",
      referenceMonth: month,
    },
  ];
}

export function getMockExtratos(month: Date): Extrato[] {
  return buildExtratos(month);
}

export function getMockHistoricalPendencies(): Extrato[] {
  const jan = new Date(2026, 0, 1);
  const dec = new Date(2025, 11, 1);

  return [
    {
      id: "h1",
      clientId: "c1",
      clientName: "Ana Souza",
      clientInitials: "AS",
      institution: "XP Investimentos",
      accountType: "Principal",
      collectionMethod: "Manual",
      status: "Pendente",
      referenceMonth: jan,
    },
    {
      id: "h2",
      clientId: "c3",
      clientName: "João Pereira",
      clientInitials: "JP",
      institution: "BTG Pactual",
      accountType: "Principal",
      collectionMethod: "Manual",
      status: "Solicitado",
      referenceMonth: jan,
      requestedAt: "2026-01-10",
    },
    {
      id: "h3",
      clientId: "c4",
      clientName: "Maria Oliveira",
      clientInitials: "MO",
      institution: "Santander Select",
      accountType: "Filho",
      collectionMethod: "Automático",
      status: "Pendente",
      referenceMonth: jan,
    },
    {
      id: "h4",
      clientId: "c2",
      clientName: "Roberto Mendes",
      clientInitials: "RM",
      institution: "Safra",
      accountType: "Holding",
      collectionMethod: "Manual",
      status: "Pendente",
      referenceMonth: dec,
    },
    {
      id: "h5",
      clientId: "c5",
      clientName: "Carlos Silva",
      clientInitials: "CS",
      institution: "Itaú Personalité",
      accountType: "Principal",
      collectionMethod: "Manual",
      status: "Solicitado",
      referenceMonth: dec,
      requestedAt: "2025-12-15",
    },
  ];
}
